version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
    command: server --console-address ":9001" /data

  storage_api:
    build:
      context: "."
    depends_on:
      - minio
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
    links:
      - "minio:minio.self.org"

volumes:
  minio_storage: {}
