version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2023-01-18T04-36-38Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc:RELEASE.2023-01-11T03-14-16Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user 12345678;
      /usr/bin/mc mb myminio/main;
      /usr/bin/mc anonymous set public myminio/main;
      exit 0;
      "

  storage_api:
    build:
      context: "."
    depends_on:
      - minio
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
    links:
      - "minio:minio.self.org"
    environment:
      MINIO_URL: minio.self.org:9000

volumes:
  minio_storage: {}
